### ISSUE TITLE
Test Minerva wallet

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#581] opened 2021-05-03 11:44 UTC
Dependent on WP, but some users asked.

Let's see if it works out of the box once WC is integrated: https://minerva.digital/

**Comment by alfetopito** [comment] 2021-05-03 17:56
Duplicate of https://github.com/gnosis/gp-swap-ui/issues/577 ?

**Closed** 2021-05-03 19:29 UTC
Labels: cow-swap-app
