### ISSUE TITLE
Wrong balance and rounding

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#280] opened 2021-03-18 11:58 UTC
# Description
I encountered some issues with the displayed balances
wrongly displayed volumes
rounding issues

# Procedure
 on RINKEBY
- I connected my MM account with Swap
- looked at the token list in the **from** section
- checked balances

# Outcome

1. Wrong balance

The Token displayed here is [USDT](https://rinkeby.etherscan.io/token/0xd9ba894e0097f8cc2bbc9d24d308b98e36dc6d02?a=0x52df85e9de71aa1c210873bcf37ec46d36c99dc2)

MM balance
<img width="359" alt="Bildschirmfoto 2021-03-18 um 12 31 31" src="https://user-images.githubusercontent.com/34510341/111619854-55676780-87e6-11eb-95a2-3c7ab900242d.png">

GP SWAP balance

<img width="408" alt="Bildschirmfoto 2021-03-18 um 12 31 43" src="https://user-images.githubusercontent.com/34510341/111619895-60ba9300-87e6-11eb-9f1a-faebe7a272be.png">
<img width="435" alt="Bildschirmfoto 2021-03-18 um 12 31 59" src="https://user-images.githubusercontent.com/34510341/111619929-67e1a100-87e6-11eb-8d6e-2b3ddfd7932c.png">
I can trade the max volume
<img width="486" alt="Bildschirmfoto 2021-03-18 um 12 32 06" src="https://user-images.githubusercontent.com/34510341/111619941-6b752800-87e6-11eb-945b-2db6ce8646a9.png">

Note: I got the tokens during this [trade](https://pr307--gpui.review.gnosisdev.com/rinkeby/orders/0x2617DBB9995548C6E10203DA2E17D6563D4C9DCAB63E4A8EBF62E3482FE4092B52DF85E9DE71AA1C210873BCF37EC46D36C99DC26040AC52)

2. Rounding
If i noticed it correctly the balance is always shown with 4 significant digits

<img width="342" alt="Bildschirmfoto 2021-03-18 um 12 38 20" src="https://user-images.githubusercontent.com/34510341/111620376-eb02f700-87e6-11eb-8559-a03ab5fc1d98.png">
<img width="400" alt="Bildschirmfoto 2021-03-18 um 12 38 27" src="https://user-images.githubusercontent.com/34510341/111620381-eb9b8d80-87e6-11eb-8496-2cd8d340c58b.png">

Shouldn't it be 248 [DAI](https://rinkeby.etherscan.io/address/0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea) or 247.96 DAI if it is rounded? 

Also for higher volumes 
MM account:
<img width="354" alt="Bildschirmfoto 2021-03-18 um 12 19 28" src="https://user-images.githubusercontent.com/34510341/111621425-45e91e00-87e8-11eb-8470-b08f4993ff34.png">
Swap Balance:
<img width="453" alt="Bildschirmfoto 2021-03-18 um 12 21 38" src="https://user-images.githubusercontent.com/34510341/111621445-4bdeff00-87e8-11eb-84e6-0a2491d172a6.png">

Shouldn't it be 157800....[DAI](https://rinkeby.etherscan.io/address/0xc7ad46e0b8a400bb3c915120d284aafba8fc4735)

**Comment by annamsgeorge** [comment] 2021-03-25 15:23
Is this purely a Rinkeby issue?

**Comment by anxolin** [comment] 2021-03-26 08:50
It shouldn't be because of rinkeby! moving this one up in the prio list to review. 
I'm surprised because we don't do much rounding that I'm aware, and I would be very surprised that uniswap has this big errors in showing the balances. 

Is possible there's a small rounding, that get bigs with amounts

**Comment by alfetopito** [comment] 2021-04-01 22:53
For the first issue, tried it on https://pr382--gpswapui.review.gnosisdev.com/#/swap with given USDT compound rinkeby token https://rinkeby.etherscan.io/token/0xd9ba894e0097f8cc2bbc9d24d308b98e36dc6d02?a=0x52df85e9de71aa1c210873bcf37ec46d36c99dc2

Could not reproduce.
Hopefully it was fixed as a side effect of some other changes?

Still, I'm able to see what you mean by rounding in the second issue with the fake DAI and even compound USDT
## Balances: 
![screenshot_2021-04-01_15-49-51.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/3a9fc9e7-51bf-4438-87e8-cf9d5b0662e1)
## In the input
![screenshot_2021-04-01_15-50-40.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/2616a587-9f3d-4f16-94ca-297f6b109d01)

I guess we inherited this from Uniswap, but agree this can be improved.
I'll look into that.

**Closed** 2021-04-06 14:26 UTC
Labels: bug, swap-app
