### ISSUE TITLE
Race conditions: 🐎 Cancelations, and Fullfillment 

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#165] opened 2021-02-19 16:13 UTC
![image](https://user-images.githubusercontent.com/2352112/108529930-4e2b6780-72d5-11eb-9fbc-7545e1130e54.png)

As you see in the image, my trade got both EXPIRED and FULFILLED.

This is obviously an error. The cancelation toast should have a small delay, giving chance to the potential fulfillment to arrive. 

Fullfillement is dependent on events, that can have some latencies. Also, blocks are not EXACTLY mined at the time they claim. So it would be wise to give some time extra for the the fulfillment to arrive. 

**TIMELINE (now):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> we show toast of EXPIRED
- 4. [5 sec later] Receive event of "Filled" ---> we show toast of FILLED

**TIMELINE (proposal):**
- 1. Send order
- 2. Filled but the event hasn't arrived yet
- 3. Expiration kicks in ---> Delay (20s) and then check order if still exipred ---> we show toast of EXPIRED
- 4. [5 sec later]  Receive event of "Filled" ---> we show toast of FILLED

## QA Testing notes
- Verify we don't get notifications twice for trades
- We can try to reduce the expiration to 1min trying to reproduce this issue
Testing URL https://pr269--gpswapui.review.gnosisdev.com/

**Comment by anxolin** [comment] 2021-02-22 17:42
[good to have] End to end: to make it reproducible we can fake the REDUX triggered action (easier than faking the eth event)
- EST: 3

- Add the delayed logic:
   - EST: 2

**Comment by MareenG** [comment] 2021-03-15 15:03
I encountered the same issue on Friday: 
[Order 1](https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x6FF2F633C8B036803CCE712D8B28C79644F4024F2BC1DD3D77E5BB9331EB22B752DF85E9DE71AA1C210873BCF37EC46D36C99DC2604B3481) got filled but was marked as expired under Recent Activity
For [Order 2](https://protocol-explorer.dev.gnosisdev.com/rinkeby/orders/0x83afcc18cef6fa8ec1b1fd312506089127739718f53ad9b7887291781e37efaa52df85e9de71aa1c210873bcf37ec46d36c99dc2604b411a*) I couldn't get any information as it couldn't be found in the Explorer 
![Bildschirmfoto 2021-03-12 um 11 40 03](https://user-images.githubusercontent.com/34510341/111173548-0a134600-85a7-11eb-8e9d-3ec15ab19b2c.png)

**Comment by anxolin** [comment] 2021-03-16 15:51
Giving prio to this, and keeping @W3stside in the loop

**Comment by W3stside** [comment] 2021-03-17 12:09
@MareenG @anxolin the Expired toast is not delayed, will implement this now.

**Comment by anxolin** [comment] 2021-03-18 14:40
@MareenG can you verify if it still reproduces in https://pr269--gpswapui.review.gnosisdev.com/

**Comment by MareenG** [comment] 2021-03-19 08:11
I did a few trades and it looks like it doesn't reproduce anymore.

**Closed** 2021-03-19 08:29 UTC
Labels: bug, swap-app
