### ISSUE TITLE
Slightly different colours in FireFox Browser

### ISSUE THREAD

**Issue by MareenG** [gnosis/gp-swap-ui#532] opened 2021-04-27 08:50 UTC
**Describe the bug**
the colours are a bit brighter in FireFox ( mainly the orange) 

**How to Reproduce**
1. visit CowSwap in Firefox Browser
<img width="526" alt="Bildschirmfoto 2021-04-27 um 10 47 52" src="https://user-images.githubusercontent.com/34510341/116213763-588b3700-a746-11eb-8eae-c8781bd4cee4.png">

**Comment by alfetopito** [comment] 2021-04-27 14:31
Yes, this was raised a few weeks back.
The issue is that FF colors are the real ones.
Chrome has by default a different color scheme. See https://stackoverflow.com/questions/38098565/color-difference-between-browsers-chromium-chrome-firefox-with-example

For now, we don't intend to do anything

cc @anxolin @michelbio

**Comment by anxolin** [comment] 2021-05-07 12:28
Closing for now, if it's not causing issues I would live it like this

**Closed by anxolin** 2021-05-07 12:28 UTC
Labels: bug, cow-swap-app
