### ISSUE TITLE
Adding menu to CowSwap (which links to "Code"; "FAQ"; "Discord") 

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-swap-ui#420] opened 2021-04-13 16:58 UTC
(This is similar to how Uniswap does it)

Adding a menu:

1) 
On the top right we can add "..." 
Example of how it would look like: 
![Screenshot 2021-04-13 at 12.47.59.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/0c5eec2b-fb66-4e1e-add2-437429bbce19)

2) 
If the user clicks on the three dots, a menu expands:

(Note, the screenshot is taken from Uniswap, we will list different things in our menu) 

![Screenshot 2021-04-13 at 12.49.18.png](https://images.zenhubusercontent.com/6059d7cca7474e5d8699f72c/74136228-45c2-4ed9-bcac-b5f46e8754fa)

3) 
The menu will include following items:

FAQ     
Code 
Discord 

4) Where the items will link:

FAQ: to be added in mark down, content still pending 
Code: https://github.com/gnosis/gp-v2-contracts 
Discord: https://discord.gg/egGzDDctuC

**Comment by anxolin** [comment] 2021-04-13 17:30
This is a duplicate of #418 #419 

Also, for the discord, we already have it (is just not visible right now). Also I think the URL should be https://chat.gnosis.io 
Maybe we can continue in the issues I created earlier and close this one. You can add any comment to those ones.

**Comment by annamsgeorge** [comment] 2021-04-13 18:34
The github URL you are linking is leading to the gnosis general chat. It should directly link to the Gnosis Protocol channel.

**Closed** 2021-04-13 18:35 UTC
