### ISSUE TITLE
Add Menu to CowSwap

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/gp-swap-ui#364] opened 2021-03-30 14:15 UTC
Moving forward we will have a few things we want to add to the UI, mainly:

- Docs
- FAQ
- Analytics (Dune Dashboard)
- Social Media (Discord) 

Rather than having separate headers for each of the section, we can have Uniswap-style like a "..." setting on the top right of CowSwap: when clicking on "..." the menu expands and the user can click on any of these items.

<img width="327" alt="Screenshot 2021-03-30 at 12 14 19" src="https://user-images.githubusercontent.com/33424780/113021330-c104e980-9183-11eb-992d-acc1eb1180e5.png">

**Comment by alfetopito** [comment] 2021-03-30 14:49
@annamsgeorge I think you created the issue before the screenshot finished loading.

**Comment by annamsgeorge** [comment] 2021-03-30 16:13
whopsie, thanks Leandro :)

**Comment by anxolin** [comment] 2021-04-14 11:53
Closing, duplicate of #418

**Closed** 2021-04-14 11:53 UTC
Labels: cow-swap-app
