### ISSUE TITLE
Price impact is slightly off

### ISSUE THREAD

**Issue by anxolin** [gnosis/gp-swap-ui#372] opened 2021-03-31 12:58 UTC
**Describe the bug**
The price impact is slightly off.

**How to Reproduce**
Go to cow swap
1. Select a token pair, input an amount
2. Write down the fee amount
3. Write down the price impact

Go to unisap
1. Select the same token pair
2. Input the amount after fees (FROM - fee)
3. Compare the price impact shown in Uniswap, with the one of CowSwap

**Screenshots** / **Expected**

FROM = 0.1 WETH
Fee = 0.00015 WETH

The actual amount traded in Uniswap for this example is
0.1 - 0.00015 = 0.09985

![image](https://user-images.githubusercontent.com/2352112/113147899-8d809880-9231-11eb-8be9-3f00606f4208.png)

If we input 0.09985 in Uniswap, we should get the same price impact as in cow swap:
![image](https://user-images.githubusercontent.com/2352112/113148228-e8b28b00-9231-11eb-8d82-2b9c9ffccd69.png)

in this case, we have 0.033% in cows wap
0.03% in uniswap

**Additional context**
I think is more than a rounding issue

**Comment by anxolin** [comment] 2021-03-31 13:06
Let's notify @MareenG when this issue is solved and testable, and move this issue into QA.

**Comment by alfetopito** [comment] 2021-03-31 15:25
Duplicate of https://github.com/gnosis/gp-swap-ui/issues/368

**Comment by MareenG** [comment] 2021-04-08 10:19
#368 is a bit different than this issue.
However for this issue I noticed that price impaction Cowswap is **always** 0.3% higher than Uniswap.

**Comment by alfetopito** [comment] 2021-04-19 21:16
You are right @MareenG , this is a different issue.
I've send out a fix for it on #457

**Closed** 2021-04-20 14:15 UTC
Labels: bug, cow-swap-app
